table 月の順番(手入力データ)
	lineageTag: 874cc159-4923-4fee-969c-d7060e03a085

	column Month
		dataType: int64
		formatString: 0
		lineageTag: a01ce11d-11e4-4704-8f1e-6c34a973d8c4
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: a5bad78f-413f-40c0-9f0c-eef4b330d762
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition 月の順番(手入力データ) = m
		mode: import
		source =
				let
				    ソース = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Jc27DQAxDALQXahdnPPPLJb3X+Mw6Z4Qggg4DP4hLdCKLvZiE0dRmtTLFtWlTQ3pUFO61JI4bKyIdXQe6+gi8wc=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Month = _t, Order = _t]),
				    変更された型 = Table.TransformColumnTypes(ソース,{{"Month", Int64.Type}, {"Order", Int64.Type}})
				in
				    変更された型

	annotation PBI_NavigationStepName = ナビゲーション

	annotation PBI_ResultType = Table

