table 'userPrincipalName (Sheet1)'
	lineageTag: 0579c622-6c8e-4482-8568-64782fc2e5cb

	column Column1
		dataType: string
		lineageTag: b7871ea4-0bf9-4b6d-b161-6ee3bbdb7484
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 426effb5-41ed-4075-80cc-b214bea7a039
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 45f93d81-ef7b-4152-849b-8f7c664b0bb1
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 17a7e146-08c9-450c-a745-0cac73b87a36
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	partition 'userPrincipalName (Sheet1)' = m
		mode: import
		source =
				let
				    ソース = Excel.Workbook(File.Contents("C:\Users\MSSPAdm01\Desktop\新しいフォルダー\RLS.xlsx"), null, false),
				    Sheet1_sheet = ソース{[Item="Sheet1",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    削除された下の行 = Table.RemoveLastN(Sheet1_sheet, each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    #"Changed Type" = Table.TransformColumnTypes(削除された下の行,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

