table テーブル1
	lineageTag: 0a647497-6d2f-481b-a53d-0a3fe55b405b

	measure Row_Number = ```
			
			CALCULATE(
			    COUNTROWS('テーブル1'),
			    FILTER(
			        ALLSELECTED ('テーブル1'), 
			        'テーブル1'[INDEX] <= MAX ('テーブル1'[INDEX])
			    )
			)
			```
		formatString: 0
		lineageTag: 7f197a2c-4467-4139-8242-9f7c98521b7d

	column ASNステータス
		dataType: int64
		formatString: 0
		lineageTag: 3febf855-af31-40b9-b175-85d83c2e01e0
		summarizeBy: sum
		sourceColumn: ASNステータス

		annotation SummarizationSetBy = Automatic

	column 入荷予定日
		dataType: dateTime
		formatString: Long Date
		lineageTag: 542dfb07-1020-4e94-892b-d6b13adae15b
		summarizeBy: none
		sourceColumn: 入荷予定日

		variation バリエーション
			isDefault
			relationship: 0fce5694-0a27-430e-9f37-46cf65e061c3
			defaultHierarchy: LocalDateTable_bfeaa33e-76eb-403d-a442-542c875c1c10.日付の階層

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 置場コード
		dataType: int64
		formatString: 0
		lineageTag: 82aafcec-47d8-4fd0-9ba3-b295b04b16b9
		summarizeBy: sum
		sourceColumn: 置場コード

		annotation SummarizationSetBy = Automatic

	column 仕入先コード
		dataType: string
		lineageTag: fd6933e7-ebb1-4d55-b7f9-76e3af7a9748
		summarizeBy: none
		sourceColumn: 仕入先コード

		annotation SummarizationSetBy = Automatic

	column ファミリーコードOriginal
		dataType: string
		lineageTag: 4e02778e-484e-47f2-846e-888da83a7918
		summarizeBy: none
		sourceColumn: ファミリーコードOriginal

		annotation SummarizationSetBy = Automatic

	column 在庫品フラグ_区分値
		dataType: int64
		formatString: 0
		lineageTag: cc640e73-876d-4546-8ecb-a9f9c893be90
		summarizeBy: sum
		sourceColumn: 在庫品フラグ_区分値

		annotation SummarizationSetBy = Automatic

	column 商品コード
		dataType: string
		lineageTag: daf10765-e41d-48d8-a76e-fad1cbfabe7a
		summarizeBy: none
		sourceColumn: 商品コード

		annotation SummarizationSetBy = Automatic

	column 出荷仕分用エリアコード
		dataType: int64
		formatString: 0
		lineageTag: 612fe8df-68da-4be7-a34e-1321ba773c98
		summarizeBy: sum
		sourceColumn: 出荷仕分用エリアコード

		annotation SummarizationSetBy = Automatic

	column 転送箱No
		dataType: string
		lineageTag: 0c5e058b-7033-409f-a5e1-c7819e72c014
		summarizeBy: none
		sourceColumn: 転送箱No

		annotation SummarizationSetBy = Automatic

	column グローバル番号
		dataType: string
		lineageTag: c9ad7fe7-b17e-404f-81d4-e7db15d91536
		summarizeBy: none
		sourceColumn: グローバル番号

		annotation SummarizationSetBy = Automatic

	column EXT_J_M_I_S_ASN_TYPE
		dataType: int64
		formatString: 0
		lineageTag: 1cfb899c-fe50-4a27-8d41-54deb19d74b7
		summarizeBy: sum
		sourceColumn: EXT_J_M_I_S_ASN_TYPE

		annotation SummarizationSetBy = Automatic

	column 統合インナーコード
		dataType: string
		lineageTag: 8ce0405d-d3fe-4238-8841-1269620df66c
		summarizeBy: none
		sourceColumn: 統合インナーコード

		annotation SummarizationSetBy = Automatic

	column iLPN番号
		dataType: string
		lineageTag: ec90599e-dec0-419c-9ec9-034444af86c7
		summarizeBy: none
		sourceColumn: iLPN番号

		annotation SummarizationSetBy = Automatic

	column 入荷検収時間
		dataType: string
		lineageTag: 257d4124-b8fe-41df-8a4b-6660789b7b83
		summarizeBy: none
		sourceColumn: 入荷検収時間

		annotation SummarizationSetBy = Automatic

	column 入荷担当者
		dataType: string
		lineageTag: 8881ad0a-1487-4c7f-aa70-9a5b67c48662
		summarizeBy: none
		sourceColumn: 入荷担当者

		annotation SummarizationSetBy = Automatic

	column 入荷予定数
		dataType: int64
		formatString: 0
		lineageTag: a4cc1a41-049c-42ab-a0dd-0a2963ce6201
		summarizeBy: sum
		sourceColumn: 入荷予定数

		annotation SummarizationSetBy = Automatic

	column 検収可能入荷予定数
		dataType: int64
		formatString: 0
		lineageTag: 12256649-9120-49d4-a30f-3cfb69e2f97d
		summarizeBy: sum
		sourceColumn: 検収可能入荷予定数

		annotation SummarizationSetBy = Automatic

	column 出荷不可数
		dataType: int64
		formatString: 0
		lineageTag: 2c84b810-f935-4ed6-a0d0-ffb711bd7515
		summarizeBy: sum
		sourceColumn: 出荷不可数

		annotation SummarizationSetBy = Automatic

	column 別納数
		dataType: int64
		formatString: 0
		lineageTag: 4cd0eb4d-3126-4fed-a8f7-804b6c9dac35
		summarizeBy: sum
		sourceColumn: 別納数

		annotation SummarizationSetBy = Automatic

	column 入荷実績数
		dataType: string
		lineageTag: bf1814a6-03ef-4643-8f02-a739e41c41b3
		summarizeBy: none
		sourceColumn: 入荷実績数

		annotation SummarizationSetBy = Automatic

	column 入庫実績数_1
		dataType: int64
		formatString: 0
		lineageTag: 9d0dc445-1cf1-4e8a-aec5-e937a7d98e8a
		summarizeBy: sum
		sourceColumn: 入庫実績数_1

		annotation SummarizationSetBy = Automatic

	column 入庫実績数_2
		dataType: string
		lineageTag: 623b8abc-9f4c-4ca5-b9ea-73c0a60b6641
		summarizeBy: none
		sourceColumn: 入庫実績数_2

		annotation SummarizationSetBy = Automatic

	column 別納フラグ
		dataType: int64
		formatString: 0
		lineageTag: 404f3b80-d078-481d-a258-09f18bae5981
		summarizeBy: sum
		sourceColumn: 別納フラグ

		annotation SummarizationSetBy = Automatic

	column 出荷不可フラグ
		dataType: int64
		formatString: 0
		lineageTag: d62e2701-d502-4285-a596-98c251a10353
		summarizeBy: sum
		sourceColumn: 出荷不可フラグ

		annotation SummarizationSetBy = Automatic

	column 得意先コード
		dataType: string
		lineageTag: a7679dfa-c115-4b08-867f-2b54f4e44f67
		summarizeBy: none
		sourceColumn: 得意先コード

		annotation SummarizationSetBy = Automatic

	column 配送先コード
		dataType: string
		lineageTag: c3f19b42-1eab-4159-8bc5-ecfe02dea1ef
		summarizeBy: none
		sourceColumn: 配送先コード

		annotation SummarizationSetBy = Automatic

	column 引渡区分
		dataType: string
		lineageTag: 9ea95827-88bb-4673-88a4-54fe4e9e4372
		summarizeBy: none
		sourceColumn: 引渡区分

		annotation SummarizationSetBy = Automatic

	column 輸出フラグ_区分値
		dataType: int64
		formatString: 0
		lineageTag: 2d3eab59-23c4-48e3-8b86-8d661da0779d
		summarizeBy: sum
		sourceColumn: 輸出フラグ_区分値

		annotation SummarizationSetBy = Automatic

	column シューター区分
		dataType: string
		lineageTag: 1131965b-582b-4e27-8879-b6572be51b58
		summarizeBy: none
		sourceColumn: シューター区分

		annotation SummarizationSetBy = Automatic

	column シューター番号
		dataType: string
		lineageTag: 174609b2-b13a-4783-b5a3-ebc883e4eba6
		summarizeBy: none
		sourceColumn: シューター番号

		annotation SummarizationSetBy = Automatic

	column ストーク有無フラグ
		dataType: string
		lineageTag: 2ec875e1-f997-4c8d-8fe3-84a2e50e1d7e
		summarizeBy: none
		sourceColumn: ストーク有無フラグ

		annotation SummarizationSetBy = Automatic

	column 仕入先名
		dataType: string
		lineageTag: 38e631d6-5e50-4f8f-a083-266a06831272
		summarizeBy: none
		sourceColumn: 仕入先名

		annotation SummarizationSetBy = Automatic

	column 入庫ロケーションコード
		dataType: string
		lineageTag: 9312f953-3b88-4aa4-828c-9ba8150a8872
		summarizeBy: none
		sourceColumn: 入庫ロケーションコード

		annotation SummarizationSetBy = Automatic

	column タイトル
		dataType: string
		lineageTag: 553e12cd-12f8-4a83-bf48-c7a4d7b264ed
		summarizeBy: none
		sourceColumn: タイトル

		annotation SummarizationSetBy = Automatic

	column ファミリーコード
		dataType: string
		lineageTag: 69687df7-dcfa-4223-9934-11e74ce67e0c
		summarizeBy: none
		sourceColumn: ファミリーコード

		annotation SummarizationSetBy = Automatic

	column 入荷種別
		dataType: string
		lineageTag: deacf1b9-e3b1-4fb2-ab6a-229e66b3a520
		summarizeBy: none
		sourceColumn: 入荷種別

		annotation SummarizationSetBy = Automatic

	column 在庫品フラグ
		dataType: string
		lineageTag: 2b1961b8-3a73-415b-a440-983dc6afe570
		summarizeBy: none
		sourceColumn: 在庫品フラグ

		annotation SummarizationSetBy = Automatic

	column 輸出フラグ_区分名
		dataType: string
		lineageTag: 17ca93dd-cc46-414d-a33d-2ff94575f1c7
		summarizeBy: none
		sourceColumn: 輸出フラグ_区分名

		annotation SummarizationSetBy = Automatic

	column 入庫エリア
		dataType: string
		lineageTag: 01bdb05a-807d-4bc6-b644-8dd374f02022
		summarizeBy: none
		sourceColumn: 入庫エリア

		annotation SummarizationSetBy = Automatic

	column ストーク有無_検索
		dataType: string
		lineageTag: 2882d5f5-cd47-4ae3-b2c4-1a1c3e73fd12
		summarizeBy: none
		sourceColumn: ストーク有無_検索

		annotation SummarizationSetBy = Automatic

	column 出荷不可フラグ_検索
		dataType: string
		lineageTag: 9bed8ca6-fb80-4ebe-a7aa-5cd93ea23137
		summarizeBy: none
		sourceColumn: 出荷不可フラグ_検索

		annotation SummarizationSetBy = Automatic

	column 別納区分_検索
		dataType: string
		lineageTag: 68fc02bf-d830-484f-8c23-5108c310bd43
		summarizeBy: none
		sourceColumn: 別納区分_検索

		annotation SummarizationSetBy = Automatic

	column LPNステータス
		dataType: string
		lineageTag: 47f03fd9-38af-4687-8240-5934d8748eaa
		summarizeBy: none
		sourceColumn: LPNステータス

		annotation SummarizationSetBy = Automatic

	column -列_コード
		dataType: string
		lineageTag: a5fbe4f2-2039-4df1-a909-d33fd06227d0
		summarizeBy: none
		sourceColumn: -列_コード

		annotation SummarizationSetBy = Automatic

	column 輸出_P
		dataType: string
		lineageTag: 85470f0f-1746-4960-a770-d5c45d5474a1
		summarizeBy: none
		sourceColumn: 輸出_P

		annotation SummarizationSetBy = Automatic

	column -列_名称
		dataType: string
		lineageTag: 68d2857d-8fde-4a84-8d78-7c5a62af0123
		summarizeBy: none
		sourceColumn: -列_名称

		annotation SummarizationSetBy = Automatic

	column -列_輸出フラグ
		dataType: string
		lineageTag: 0ed3172a-41e1-42fa-8a46-63f1677b3313
		summarizeBy: none
		sourceColumn: -列_輸出フラグ

		annotation SummarizationSetBy = Automatic

	column 入荷予定日_計算
		dataType: int64
		formatString: 0
		lineageTag: 0da95e5d-accf-4684-8649-a52b138c68b0
		summarizeBy: sum
		sourceColumn: 入荷予定日_計算

		annotation SummarizationSetBy = Automatic

	column INDEX
		dataType: int64
		formatString: 0
		lineageTag: 9e6fbc08-fb15-4bdb-8cb2-e7b753a39b10
		summarizeBy: sum
		sourceColumn: INDEX

		annotation SummarizationSetBy = User

	partition テーブル1 = m
		mode: import
		source =
				let
				    ソース = Excel.Workbook(Web.Contents("https://microsoftapc.sharepoint.com/teams/CNX-HybridBI/Shared%20Documents/Case%20Assignment/MS_MainQuery.xlsx"), null, true),
				    テーブル1_Table = ソース{[Item="テーブル1",Kind="Table"]}[Data],
				    変更された型 = Table.TransformColumnTypes(テーブル1_Table,{{"ASNステータス", Int64.Type}, {"入荷予定日", type date}, {"置場コード", Int64.Type}, {"仕入先コード", type any}, {"ファミリーコードOriginal", type text}, {"在庫品フラグ_区分値", Int64.Type}, {"商品コード", type text}, {"出荷仕分用エリアコード", Int64.Type}, {"転送箱No", type any}, {"グローバル番号", type any}, {"EXT_J_M_I_S_ASN_TYPE", Int64.Type}, {"統合インナーコード", type text}, {"iLPN番号", type text}, {"入荷検収時間", type any}, {"入荷担当者", type any}, {"入荷予定数Original", Int64.Type}, {"検収可能入荷予定数_1", Int64.Type}, {"検収可能入荷予定数_2", type any}, {"出荷不可数_1", Int64.Type}, {"出荷不可数_2", type any}, {"別納数_1", Int64.Type}, {"別納数_2", type any}, {"入荷実績数_1", type any}, {"入庫実績数_1", Int64.Type}, {"入庫実績数_2", type any}, {"別納フラグ", Int64.Type}, {"出荷不可フラグ", Int64.Type}, {"得意先コード", type any}, {"配送先コード", type any}, {"引渡区分", type any}, {"輸出フラグ_区分値", Int64.Type}, {"シューター区分", type text}, {"シューター番号", type text}, {"ストーク有無フラグ", type any}, {"仕入先名", type any}, {"入庫ロケーションコード", type any}, {"タイトル", type text}, {"ファミリーコード", type text}, {"入荷種別", type text}, {"在庫品フラグ", type text}, {"輸出フラグ_区分名", type text}, {"入庫エリア", type any}, {"ストーク有無_検索", type text}, {"出荷不可フラグ_検索", type text}, {"別納区分_検索", type text}, {"LPNステータス", type text}, {"-列_コード", type text}, {"輸出_P", type text}, {"-列_名称", type text}, {"-列_輸出フラグ", type text}, {"入荷実績数_2", type any}, {"入荷予定日_計算", Int64.Type}}),
				    #"名前が変更された列 " = Table.RenameColumns(変更された型,{{"入荷予定数Original", "入荷予定数"}}),
				    削除された列 = Table.RemoveColumns(#"名前が変更された列 ",{"検収可能入荷予定数_2"}),
				    #"名前が変更された列 1" = Table.RenameColumns(削除された列,{{"検収可能入荷予定数_1", "検収可能入荷予定数"}}),
				    削除された列1 = Table.RemoveColumns(#"名前が変更された列 1",{"入荷実績数_2", "出荷不可数_2"}),
				    #"名前が変更された列 2" = Table.RenameColumns(削除された列1,{{"出荷不可数_1", "出荷不可数"}}),
				    削除された列2 = Table.RemoveColumns(#"名前が変更された列 2",{"別納数_2"}),
				    #"名前が変更された列 3" = Table.RenameColumns(削除された列2,{{"別納数_1", "別納数"}, {"入荷実績数_1", "入荷実績数"}}),
				    並べ替えられた行 = Table.Sort(#"名前が変更された列 3",{{"入荷予定日", Order.Ascending}}),
				    追加されたインデックス = Table.AddIndexColumn(並べ替えられた行, "インデックス", 1, 1, Int64.Type),
				    #"名前が変更された列 4" = Table.RenameColumns(追加されたインデックス,{{"インデックス", "INDEX"}})
				in
				    #"名前が変更された列 4"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = ナビゲーション

